site_name: Calendar
site_url: https://tiogars.github.io/calendar/docs/
repo_name: tiogars/calendar
repo_url: https://github.com/tiogars/calendar
edit_uri: edit/main/docs/
site_description: Documentation for the Calendar Print application
site_author: Tiogars
copyright: © 2025, Tiogars
docs_dir: docs
site_dir: site_output

nav:
  - Home: index.md
  - Features: 01-features/index.md
  - Edition Modes: 02-edition-modes/index.md
  - Pages & Screenshots: 03-pages-and-screen-captures/index.md
  - Technical Dependencies: 04-technical-dependencies/index.md
  - CI/CD Deployment: 05-ci-cd-deployment/index.md

theme:
  name: material
  custom_dir: docs/overrides
  icon:
    repo: fontawesome/brands/github
  features:
    - content.action.edit
    - content.action.view
  language: en
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference

plugins:
  - search
  # https://pypi.org/project/mkdocs-with-pdf/
  - to-pdf:
      author: Tiogars
      back_cover: false
      copyright: Copyright © Tiogars 2025
      cover: true
      cover_subtitle: Documentation
      cover_title: Calendar
      output_path: tiogars.calendar.pdf
      event_hook: pdf_event_hook
  - print-site:
      add_to_navigation: false
      print_page_title: 'Print Site'
      add_table_of_contents: true
      toc_title: 'Table of Contents'
      toc_depth: 6
      add_full_urls: true
      enumerate_headings: true
      enumerate_figures: true
      add_cover_page: true
      path_to_pdf: "tiogars.calendar.pdf"
      include_css: true
      enabled: true
      exclude: []

markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
